### ISSUE TITLE
Encounter difficulties in running

### ISSUE THREAD

**Issue by Chanzhaoyu** [thisuxhq/fli.so#11]
When I ran to the second step of the documentation, I encountered a pocketbase problem and still haven't been able to solve it for several hours.

Pocketbase version: 0.22.27.

File structure:

![image](https://github.com/user-attachments/assets/c565d6ce-0eb8-47a3-931c-f174a38923f5)

Console error:

![image](https://github.com/user-attachments/assets/3742c9f6-c959-4f55-89f8-57cb3a466de0)

![image](https://github.com/user-attachments/assets/916cb58c-c265-4cd2-9d4c-8417c512c678)

Thank you very much.

**Comment by build3r** [comment]
the mistake in the script
It should be 
`"pocketbase:dev": "pocketbase/pocketbase serve --http=127.0.0.1:8090 --dir=pocketbase/pb_data",`

**Comment by walkxcode** [comment]
This issue is still there and not resolved.

![Image](https://github.com/user-attachments/assets/5c3cd972-04b8-4976-b56b-221a93d2669b)
