### ISSUE TITLE
Why does the .env.example have the pound symbol in it?

### ISSUE THREAD

**Issue by dillfrescott** [thisuxhq/fli.so#3]
I just noticed this and it seems odd and out of place.

Here: https://github.com/thisuxhq/fli.so/blob/7cf41aa82aa21146c3fe93b9bbc5b1188fb1c3fb/.env.example#L1

**Comment by dillfrescott** [comment]
it also has an upside down ! and also a trademark symbol. I might add.

**Comment by Spikeysanju** [comment]
@dillfrescott typo mistake. fixing it

**Comment by Spikeysanju** [comment]
@dillfrescott Please pull the latest version. it's fixed already!

**Comment by dillfrescott** [comment]
Okay thanks!
