### ISSUE TITLE
Isn't the PUBLIC_POCKETBASE_URL from docker-compose.yml suppose to take the string from .env file? 

### ISSUE THREAD

**Issue by SamWang8891** [thisuxhq/fli.so#6]
**Describe the bug**
I suppose the PUBLIC_POCKETBASE_URL from docker-compose.yml taking the string from the .env file, so user don't have to go to that yaml file in order to change it. 

**To Reproduce**
Just see the two files: docker-compose.yml and .env.example

**Expected behavior**
Just like how I described in the "Describe the bug" section.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I'm not sure how these parameter work in cause I'm not familiar with pocket base, so plz do take a look at https://github.com/thisuxhq/fli.so/issues/5.

**Comment by SamWang8891** [comment]
<img width="865" alt="Screenshot 2024-12-03 at 7 53 44 AM" src="https://github.com/user-attachments/assets/cb182ae8-e236-4358-b4d4-08aadbc04219">

**Comment by SamWang8891** [comment]
<img width="865" alt="Screenshot 2024-12-03 at 7 53 44 AM" src="https://github.com/user-attachments/assets/d126237a-fe00-4f09-804f-7ec57a7abc81">
<img width="865" alt="Screenshot 2024-12-03 at 7 54 43 AM" src="https://github.com/user-attachments/assets/2f87417a-70bf-4e57-844a-801170313f2e">

**Comment by Spikeysanju** [comment]
@SamWang8891 We're currently working on a documentation page to help set up fli.so with easy-to-follow instructions. Check out this [comment](https://github.com/thisuxhq/fli.so/issues/5#issuecomment-2514154644) for more details.
